### ISSUE TITLE
ClosedFileSystemException when comparing two JARs using GAV option of Standalone Executor

### ISSUE THREAD

**Issue by marcphilipp** [revapi/revapi#111]
This currently happens on macOS:

```xml
~/Desktop/revapi-0.6.4                                                                             
▶ ./revapi.sh --extensions=org.revapi:revapi-java:0.14.4,org.revapi:revapi-reporter-text:0.8.2 --old-gavs=org.junit.jupiter:junit-jupiter-api:5.0.1 --new-gavs=org.junit.jupiter:junit-jupiter-api:5.0.2
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.modules.ClassLoaderLocalLoader$1 (file:/Users/marcph/Desktop/revapi-0.6.4/lib/jboss-modules-1.3.0.Final-forge.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jboss.modules.ClassLoaderLocalLoader$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Analysis results
----------------

Old API: junit-jupiter-api-5.0.1.jar
New API: junit-jupiter-api-5.0.2.jar

com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /private/var/folders/xd/2hkclygd2536_66h1kndxn0snm_29k/T/revapi-java1060717640624908068/lib/0-4d2f95ba-8724-313d-a264-8ef5b87cf52f(/org/junit/jupiter/api/AssertArrayEquals.class)
  unable to access file: java.nio.file.ClosedFileSystemException
  Please remove or make sure it appears in the correct subdirectory of the classpath.
	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.badClassFile(ClassReader.java:278)
	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2761)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:348)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:285)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1314)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$MethodSymbol.params(Symbol.java:1893)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$MethodSymbol.getParameters(Symbol.java:1976)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$MethodSymbol.getParameters(Symbol.java:1623)
	at org.revapi.java.spi.Util$3.visitVariable(Util.java:476)
	at org.revapi.java.spi.Util$3.visitVariable(Util.java:459)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1561)
	at org.revapi.java.spi.Util.toHumanReadableString(Util.java:728)
	at org.revapi.java.model.JavaElementBase.createFullHumanReadableString(JavaElementBase.java:139)
	at org.revapi.java.model.JavaElementBase.getFullHumanReadableString(JavaElementBase.java:129)
	at org.revapi.java.model.JavaElementBase.toString(JavaElementBase.java:171)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.revapi.Stats$Tuple2.toString(Stats.java:162)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.revapi.Stats$Collector.toString(Stats.java:116)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.revapi.Stats.asString(Stats.java:63)
	at org.revapi.AnalysisResult.close(AnalysisResult.java:118)
	at org.revapi.standalone.Main.$closeResource(Main.java:318)
	at org.revapi.standalone.Main.run(Main.java:343)
	at org.revapi.standalone.Main.main(Main.java:262)
```

**Comment by metlos** [comment]
This seems to be specific to Java9. Looks like the Java compiler no longer tolerates accessing elements after the compile session was closed.

**Comment by metlos** [comment]
As a workaround, I think you could merely reconfigure the logging in the `$REVAPI_STANDALONE_DIR/conf/logback.xml` and change the root logger to capture just INFO level, not "all".
