### ISSUE TITLE
Standalone fails to install artifacts on local repo

### ISSUE THREAD

**Issue by paoloantinori** [revapi/revapi#177]
```bash
20:47:07 (..ta/sw/revapi-0.9.4)$ ./revapi.sh --extensions=org.revapi:revapi-java:0.11.2,org.revapi:revapi-reporting-text:0.10.2    --old-gavs=org.apache.camel:camel-support:3.0.1 --new-gavs==org.apache.camel:camel-support:3.1.0 -D revapi.reporter.text.minSeverity=BREAKING --remote-repositories='https://repo.maven.apache.org/maven2'
20:48:22.653 INFO  Downloading checked archives
Exception in thread "main" java.lang.IllegalArgumentException: New API Maven artifact Could not transfer artifact =org.apache.camel:camel-support:jar:3.1.0 from/to @@~/.m2/repository@@ (file:/home/pantinor/.m2/repository/): Cannot access file:/home/pantinor/.m2/repository/ with type local using the available connector factories: BasicRepositoryConnectorFactory
	at org.revapi.standalone.Main.convertGavs(Main.java:438)
	at org.revapi.standalone.Main.main(Main.java:260)
```

**Comment by paoloantinori** [comment]
my bad, there was a double equals on my invocation

**Comment by metlos** [comment]
`revapi-0.11.2` is quite ancient. Please consider upgrading..

**Comment by metlos** [comment]
`revapi-java:0.11.2` that is...
