### ISSUE TITLE
Option to fail the build when the artifact to compare to isn't found

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#22]
I get:

````
[INFO] --- revapi-maven-plugin:0.4.1:check (revapi-check) @ xwiki-rendering-archetype-macro ---
Downloading: http://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/rendering/xwiki-rendering-archetype-macro/7.4.2/xwiki-rendering-archetype-macro-7.4.2.maven-archetype
Downloading: https://repo.maven.apache.org/maven2/org/xwiki/rendering/xwiki-rendering-archetype-macro/7.4.2/xwiki-rendering-archetype-macro-7.4.2.maven-archetype
[WARNING] Failed to resolve old artifacts: Could not find artifact org.xwiki.rendering:xwiki-rendering-archetype-macro:maven-archetype:7.4.2 in xwiki-releases (http://nexus.xwiki.org/nexus/content/groups/public). The API analysis will not proceed.
org.revapi.maven.Analyzer$MarkerException: Could not find artifact org.xwiki.rendering:xwiki-rendering-archetype-macro:maven-archetype:7.4.2 in xwiki-releases (http://nexus.xwiki.org/nexus/content/groups/public)
	at org.revapi.maven.Analyzer$2.apply(Analyzer.java:255)
	at org.revapi.maven.Analyzer$2.apply(Analyzer.java:248)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.revapi.maven.Analyzer.resolveArtifacts(Analyzer.java:273)
	at org.revapi.maven.Analyzer.analyze(Analyzer.java:320)
	at org.revapi.maven.AbstractRevapiMojo.analyze(AbstractRevapiMojo.java:181)
	at org.revapi.maven.CheckMojo.execute(CheckMojo.java:42)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.xwiki.rendering:xwiki-rendering-archetype-macro:maven-archetype:7.4.2 in xwiki-releases (http://nexus.xwiki.org/nexus/content/groups/public)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.revapi.maven.utils.ArtifactResolver.resolveArtifact(ArtifactResolver.java:62)
	at org.revapi.maven.Analyzer$BuildAwareArtifactResolver.resolveArtifact(Analyzer.java:448)
	at org.revapi.maven.Analyzer$2.apply(Analyzer.java:252)
	... 34 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.xwiki.rendering:xwiki-rendering-archetype-macro:maven-archetype:7.4.2 in xwiki-releases (http://nexus.xwiki.org/nexus/content/groups/public)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 40 more
[INFO] API checks completed without failures.
````

But this is not failiing the build so it'll go mostly unnoticed. I'd like an option to have the build fail. Is that possible? :) Thanks!

**Comment by metlos** [comment]
Added two new options `failOnUnresolvedArtifacts` and `failOnUnresolvedDependencies` both defaulting to false to retain compatibility with the previous behavior.
