### ISSUE TITLE
release artifacts of the CLI use a SNAPSHOT of the API

### ISSUE THREAD

**Issue by jtnord** [revapi/revapi#229]
the latest CLI (https://repo1.maven.org/maven2/org/revapi/revapi-standalone/0.10.2/revapi-standalone-0.10.2-standalone.zip) uses 0.13.0_SNAPSHOT of `rg.revapi:revapi:jar` whereas the latest reporters (published the same day_ depend on 0.13.2.

this produces warnings when running the CLI with the reporters, and is possibly the cause of the `NoSuchMethodError` that comes next.

```
>c:\Java\revapi-0.10.2\revapi.bat  --extensions=org.revapi:revapi-java:0.23.2,org.revapi:revapi-reporter-text:0.13.2 --old-gavs com.google.guava:guava:11.0.1  --new-gavs com.google.guava:guava:30.1.1-jre
15:13:15.843 INFO  Downloading checked archives
15:13:16.083 INFO  Downloading extensions
15:13:16.323 WARN  Detected version conflict in dependencies of extension org.revapi:revapi-reporter-text:jar:0.13.2. The extension depends on org.revapi:revapi:jar:0.13.2 while the CLI has org.revapi:revapi:jar:0.13.0-SNAPSHOT on global classpath. This will likely cause problems.
15:13:16.618 WARN  Detected version conflict in dependencies of extension org.revapi:revapi-reporter-file-base:jar:0.3.2. The extension depends on org.revapi:revapi:jar:0.13.2 while the CLI has org.revapi:revapi:jar:0.13.0-SNAPSHOT on global classpath. This will likely cause problems.
15:13:16.748 WARN  Detected version conflict in dependencies of extension org.revapi:revapi-java:jar:0.23.2. The extension depends on org.revapi:revapi:jar:0.13.2 while the CLI has org.revapi:revapi:jar:0.13.0-SNAPSHOT on global classpath. This will likely cause problems.
15:13:16.878 WARN  Detected version conflict in dependencies of extension org.revapi:revapi-java-spi:jar:0.22.2. The extension depends on org.revapi:revapi:jar:0.13.2 while the CLI has org.revapi:revapi:jar:0.13.0-SNAPSHOT on global classpath. This will likely cause problems.
15:13:17.283 INFO  Starting analysis
15:13:17.313 WARN  At least one of `minLevel` and `minCriticality` should to be defined. Defaulting to the obsolete behavior of reporting all potentially breaking elements.
15:13:17.433 WARN  The `revapi.ignore` extension is deprecated. Consider using the `revapi.differences` instead.
15:13:17.433 WARN  The `revapi.reclassify` extension is deprecated. Consider using the `revapi.differences` instead.
15:13:21.248 INFO  Analysis took 3965ms.
Exception in thread "main" java.lang.NoSuchMethodError: org.revapi.CorrespondenceComparatorDeducer.editDistance(Ljava/util/function/BiPredicate;)Lorg/revapi/CorrespondenceComparatorDeducer;
        at org.revapi.java.JavaApiAnalyzer.lambda$getCorrespondenceDeducer$3(JavaApiAnalyzer.java:161)
        at org.revapi.Revapi.analyze(Revapi.java:403)
        at org.revapi.Revapi.analyze(Revapi.java:436)
        at org.revapi.Revapi.analyze(Revapi.java:436)
        at org.revapi.Revapi.analyzeWith(Revapi.java:333)
        at org.revapi.Revapi.analyze(Revapi.java:202)
        at org.revapi.standalone.Main.run(Main.java:406)
        at org.revapi.standalone.Main.main(Main.java:275)
```

Dependency info https://search.maven.org/artifact/org.revapi/revapi-standalone/0.10.2/jar shows the property used for the version of the API dependency is still using a SNAPSHOT -> `<version.org.revapi.revapi>0.13.0-SNAPSHOT</version.org.revapi.revapi>`

**Comment by jtnord** [comment]
replaceing the bundled `revapi-0.13.0-SNAPSHOT.jar` with `revapi-0.13.2.jar` downloaded from maven central fixes the NoSuchMethodError

**Comment by metlos** [comment]
Thanks for reporting this. I've noticed this some time ago when I started doing scripted releases. Hopefully will get this sorted with the next release.

**Comment by metlos** [comment]
`revapi-standalone-0.11.0` should no longer exhibit this and only depend on released artifact versions. Again, thanks for reporting this!
