### ISSUE TITLE
NullPointerException at org.revapi.base.FileArchive.getName(FileArchive.java:44)

### ISSUE THREAD

**Issue by pzygielo** [revapi/revapi#231]
This works:
```shell
$ revapi.sh \
  --extensions=org.revapi:revapi-java:0.24.1,org.revapi:revapi-reporter-text:0.14.1 \
  --old-gav jakarta.jms:jakarta.jms-api:2.0.3 \
  --new-gav jakarta.jms:jakarta.jms-api:3.0.0 \
  --cache-dir=/tmp/revapi-cache
```
and as expected - reports many of:
```
old: interface javax.jms.XATopicSession
new: <none>
java.class.removed: Class was removed.
SOURCE: BREAKING, BINARY: BREAKING
```

However - with similar expectations as above - when executed as:
```shell
$ revapi.sh \
  --extensions=org.revapi:revapi-java:0.24.1,org.revapi:revapi-reporter-text:0.14.1 \
  --old-gav jakarta.faces:jakarta.faces-api:2.3.2 \
  --new-gav jakarta.faces:jakarta.faces-api:3.0.0 \
  --cache-dir=/tmp/revapi-cache 
```
I'm getting
```
17:55:21.650 INFO  Downloading checked archives
17:55:23.631 INFO  Downloading extensions
17:55:25.388 INFO  Starting analysis
17:55:25.448 WARN  At least one of `minLevel` and `minCriticality` should to be defined. Defaulting to the obsolete behavior of reporting all potentially breaking elements.
Analysis results
----------------

Old API: jakarta.faces-api-2.3.2.jar
New API: jakarta.faces-api-3.0.0.jar

17:55:25.780 INFO  Analysis took 391ms.
java.lang.NullPointerException
	at org.revapi.base.FileArchive.getName(FileArchive.java:44)
	at org.revapi.API.addArchivesToString(API.java:188)
	at org.revapi.API.toString(API.java:173)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at org.revapi.Revapi.analyzeWith(Revapi.java:302)
	at org.revapi.Revapi.analyze(Revapi.java:212)
	at org.revapi.standalone.Main.run(Main.java:401)
	at org.revapi.standalone.Main.main(Main.java:275)
```

revapi: 0.11.1
java: 11.0.11

**Comment by metlos** [comment]
Thanks for reporting this! I've improved the validation of the gavs and it turns out there seems to be a problem resolving `org.glassfish:jakarta.faces:3.0.0-RC5`.

**Comment by pzygielo** [comment]
Thanks for checking and the fix.
