### ISSUE TITLE
Aggregated plain text report for copy-pasting in release notes

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#29]
On the XWiki project, we put all backward compatibility violations in our Release not'es. For example this is what we had for our last release that was using CLIRR: http://www.xwiki.org/xwiki/bin/view/ReleaseNotes/ReleaseNotesXWiki80#HAPIBreakages

Now that we'd like to move to revapi we need a simple way to generate such a report (without having to manually go over the logs of the hundreds of maven modules that we have).

This is currently our process for generating those CLIRR reports during a release:
http://dev.xwiki.org/xwiki/bin/view/ReleasePlans/ReleasePlanHelp#HManually

Namely:
- Find all places where we have clirr excludes in our poms and remove them (so that violations are genertaed)
- run clirr on all modules and output the result in a file for each module
- aggregate the content from all those violations and copy paste in our releases notes by manually matching the justifications for the excludes

Do you think you could help us come up with a better automated solution with revapi?

What would help I guess is the ability to generate an aggregated (as in maven reactor) plain text report of violations for all modules and without having to remove the violations

Thanks a lot

BTW when I run "mvn clean reapi:report" from the command line on xwiki-commons/xwiki-commons-core/xwiki-commons-component, I get:

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.4.2:report (default-cli) on project xwiki-commons-component-api: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.4.2:report failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.revapi:revapi-maven-plugin:0.4.2:report (default-cli) on project xwiki-commons-component-api: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.4.2:report failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.4.2:report failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.NullPointerException
    at org.revapi.maven.ReportMojo.getDescription(ReportMojo.java:263)
    at org.revapi.maven.ReportMojo.executeReport(ReportMojo.java:235)
    at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
    at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
```

**Comment by metlos** [comment]
That is a good idea.

Currently, I think revapi could get you half way there.. You can "externalize" your API changes into a separate revapi configuration file (you'd configure revapi along the lines of http://revapi.org/modules/revapi-maven-plugin/examples/multi-file-configuration.html and put your API changes in a separate config file like https://github.com/revapi/revapi/blob/5ccf3788a09a015b927fea97abe14e7265642ddc/revapi-java-spi/api-changes.json). You could then write a simple script that would parse them and create a text report.

The `revapi:report` goal is very rudimentary right now but I think it could or maybe even should be used for this purpose. I'll think about some way we could get there.

Btw. I'm not very experienced in writing maven plugins and even less in writing reporting plugins. It'd be great if you could share some experience with writing or using them so that the end result is usable.

**Comment by metlos** [comment]
The NPE comes from the fact that for the report to work, you need to have your artifacts built. So I hope that `mvn clean package revapi:report` should work.

The error reporting could be improved, I admit ;)

**Comment by vmassol** [comment]
FTR I'm hesitating between 2 routes:
* Implementing http://jira.xwiki.org/browse/XCOMMONS-947
* Continuing in the direction of this issue, i.e.
** Generate an aggregated plain text report for all modules (this issue)
** Publish it to an xwiki.org page using some maven http plugin (or an ant task) using the XWiki REST API

This other route is probably better since it:
- Keeps the config versioned in the SCM, close to the code
- Doesn't have any offline issue and xwiki can be built and have backward-compat checks done while offline

**Comment by vmassol** [comment]
I've stopped hesitating, this is the best way.

**Comment by vmassol** [comment]
> Btw. I'm not very experienced in writing maven plugins and even less in writing reporting plugins. It'd be great if you could share some experience with writing or using them so that the end result is usable.

What I'd do:

* In the check mojo: 
** Add a mojo parameter to configure a file where to also output the violations. If this file already exists, there could a config option to append to it, or replace it. This would allow to have all violations in a single file.
** Add a mojo parameter to ignore some excludes from the revapi configuration. Since you consider config as a black box from the POV of the maven plugin, you'd need to add an option in the java api of revapi for that I guess. Now this parameter would need to explicit mention which path in the json to ignore (since we want to not ignore the default excludes we have in XWiki for example ;)).
** The user would execute the check mojo with a single location specified and with ignoring the custom excludes in order to generate an output for the expected violations.

* In the report mojo:
** Add a parameter to specify the location of a violation output file (the one generated from the check mojo). This would be the input for the report  mojo
** Add a parameter to specify which reports to generate: html, text

WDYT?

**Comment by metlos** [comment]
I think this is doable now with `report-aggregate` goal and a custom template for text reporter configured to append to output.
