### ISSUE TITLE
Add ability to share the revapi configuration between several Maven pom.xml files

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#65]
On XWiki we have some common revapi config that we'd like to share between modules to avoid duplication.

For example:
https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/pom.xml#L153

Usually other maven plugins (such as the maven-remote-resources-plugin) would allow you to defined a plugin dependency and that dep will contain the common config to reuse. Example here: https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-pom/pom.xml#L72

It would be nice if revapi supported something similar for maven, allowing to define the config in one place but also allowing to **add** new items to the config in the pom "inheriting" from the common config.

WDYT?

**Comment by metlos** [comment]
Now that #19 is in, the analysis configuration can be specified in XML so inheritance should at last be possible...

I've not yet looked at reuse-by-dependency - need to see how that could work with revapi. It's a neat idea that hasn't crossed my mind yet :)

**Comment by metlos** [comment]
Implemented in `revapi-maven-plugin-0.9.0`.

**Comment by vmassol** [comment]
Could you let me know how to use it? I've seen https://github.com/revapi/revapi/commit/616c3a673d56f56c39765b45cc775c84a10a8d22#diff-cc2b30077989570b15980b4683b79b2cR36 but I have some doubts.

So in my top level pom I have put:

`````
      <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.xwiki.commons</groupId>
            <artifactId>xwiki-commons-tool-license-resources</artifactId>
            <version>9.2-SNAPSHOT</version>
          </dependency>
        </dependencies>
        <configuration>
          <analysisConfigurationFiles>
            <configurationFile>
              <resource>revapi.json</resource>
            </configurationFile>
          </analysisConfigurationFiles>
        </configuration>
      </plugin>
````

Which means it's going to be inherited by all submodules. And those submodules just need to add the extra config.

Can I just used:

`````
      <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <configuration>
          <analysisConfiguration><![CDATA[
            {
              "revapi": {
                "ignore" : [
                  {
                    "code": "java.field.serialVersionUIDUnchanged",
                    "old": "field org.xwiki.extension.ExtensionId.serialVersionUID",
                    "new": "field org.xwiki.extension.ExtensionId.serialVersionUID",
                    "package": "org.xwiki.extension",
                    "classSimpleName": "ExtensionId",
                    "fieldName": "serialVersionUID",
                    "elementKind": "field",
                    "justification": "The ExtensionId.hashCode field was wrongly introduced as non transient and
                      deserializing some data serialized with the previous XWiki version should at worse initialize it
                      to the default value which is -1 and ok. In any case we're using the ignoreUnknownElements()
                      option on the XStream side so we should be ok anyway!"
                  },
                  {
                    "code": "java.field.serialVersionUIDUnchanged",
                    "old": "field org.xwiki.extension.job.AbstractExtensionRequest.serialVersionUID",
                    "new": "field org.xwiki.extension.job.AbstractExtensionRequest.serialVersionUID",
                    "package": "org.xwiki.extension.job",
                    "classSimpleName": "AbstractExtensionRequest",
                    "fieldName": "serialVersionUID",
                    "elementKind": "field",
                    "justification": "Does not break anything: new static field with no impact on the serialization/unserialization"
                  }

                  // Add more ignores below...
                ]
              }
            }
          ]]></analysisConfiguration>
        </configuration>
      </plugin>
````

Testing now... Thanks

**Comment by vmassol** [comment]
hmm doesn't seem to work so I'm not using the right way. I've also tested:

`````
      <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <configuration>
          <analysisConfigurationFiles>
            <analysisConfiguration><![CDATA[
            {
              "revapi": {
                "ignore" : [
                  {
                    "code": "java.field.serialVersionUIDUnchanged",
                    "old": "field org.xwiki.extension.ExtensionId.serialVersionUID",
                    "new": "field org.xwiki.extension.ExtensionId.serialVersionUID",
                    "package": "org.xwiki.extension",
                    "classSimpleName": "ExtensionId",
                    "fieldName": "serialVersionUID",
                    "elementKind": "field",
                    "justification": "The ExtensionId.hashCode field was wrongly introduced as non transient and
                      deserializing some data serialized with the previous XWiki version should at worse initialize it
                      to the default value which is -1 and ok. In any case we're using the ignoreUnknownElements()
                      option on the XStream side so we should be ok anyway!"
                  },
                  {
                    "code": "java.field.serialVersionUIDUnchanged",
                    "old": "field org.xwiki.extension.job.AbstractExtensionRequest.serialVersionUID",
                    "new": "field org.xwiki.extension.job.AbstractExtensionRequest.serialVersionUID",
                    "package": "org.xwiki.extension.job",
                    "classSimpleName": "AbstractExtensionRequest",
                    "fieldName": "serialVersionUID",
                    "elementKind": "field",
                    "justification": "Does not break anything: new static field with no impact on the serialization/unserialization"
                  }

                  // Add more ignores below...
                ]
              }
            }
          ]]></analysisConfiguration>
          </analysisConfigurationFiles>
        </configuration>
      </plugin>
`````

but it seems the excludes are not taken into account so that must be a wrong config too.

**Comment by metlos** [comment]
`analysisConfiguration` should not be embedded inside `analysisConfigurationFiles`. Those should be siblings.

So to use all the new stuff in `0.9.0`, I'd put this in the child pom:
```xml
<plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <configuration>
          <analysisConfiguration>
            <revapi.ignore>
              <item>
                <code>java.field.serialVersionUIDUnchanged</code>
                <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                <justification>The ExtensionId.hashCode field was wrongly introduced as non transient and
                      deserializing some data serialized with the previous XWiki version should at worse initialize it
                      to the default value which is -1 and ok. In any case we're using the ignoreUnknownElements()
                      option on the XStream side so we should be ok anyway!</justification>
              </item>
              <item>
                <code>java.field.serialVersionUIDUnchanged</code>
                <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                <justification>Does not break anything: new static field with no impact on the serialization/unserialization</justification>
              </item>
            </revapi.ignore>
          </analysisConfiguration>
        </configuration>
      </plugin>
```

**Comment by metlos** [comment]
ah, I see you tried something like that, too...

From the looks of it, this should work... not sure what is wrong here...

**Comment by vmassol** [comment]
ah that's nice, didn't know you could avoid json, trying

**Comment by vmassol** [comment]
Actually it's nice but revapi reports json when there are failure so we usually just copy paste what it reports ;)

**Comment by metlos** [comment]
@vmassol, there even a new goal: `mvn revapi:convert-config-to-xml` ;) http://revapi.org/modules/revapi-maven-plugin/convert-config-to-xml-mojo.html

**Comment by vmassol** [comment]
nice :)

**Comment by metlos** [comment]
> Actually it's nice but revapi reports json when there are failure so we usually just copy paste what it reports ;)

I wasn't sure what to do here... Xml is I think preferable now that Revapi can handle it, but on the other hand, people with existing setups, could no longer just copy paste the output, because it would suddenly be XML and not JSON that they are set up with...

**Comment by vmassol** [comment]
Ok so using the XML format fails too. Looking at the errors it seems it's not using the common json config from the parent or that config is not correctly defined. I have the following in my revapi.json file:

`````
{
  "revapi": {
    "java": {
      "filter": {
        "packages": {
          "regex": true,
          // Note that we currently don't include non-XWiki classes in the checks, the reason being that
          // third-party deps break backward-compat or source compat all the time and we would need to have
          // excludes all the time. So we currently trust them that the breakages are not real breakages
          // that will affect us. We should probably improve this in the future.
          "include": [
            "org\\.xwiki\\..*"
          ],
          "exclude": [
            "org\\.xwiki\\..*\\.internal(\\..*)?",
            "org\\.xwiki\\..*\\.test(\\..*)?"
          ]
        }
      }
    },
    "ignore": [
      {
        "code": "java.annotation.removed",
        "annotationType": "org.xwiki.stability.Unstable",
        "justification": "These are marker annotations that have no semantical consequences."
      },
      {
        "code": "java.annotation.added",
        "annotationType": "org.xwiki.stability.Unstable",
        "justification": "Not a breakage. Indicates API readiness only and has no semantic consequences."
      },
      // The "externalClassExposedInAPI" check is used to detect code smells. It's documented as:
      // "This is reported for classes from dependencies that are exposed in the API (for example as a
      // return value). This is generally discouraged practice because it makes updating the dependency
      // version a more complex task (you want a bugfix but you don’t want the changed API to leak to your
      // users)."
      // In the case of XWiki it's not a problem because we release all modules together using the same
      // versioning. However we still want to detect this for non XWiki classes.
      {
        "regex": true,
        "code": "java\.class\.externalClassExposedInAPI",
        "package": "org\.xwiki\..*",
        "justification": "Dragging of other XWiki types to the API is OK."
      }
    ]
  }
}
`````

**Comment by vmassol** [comment]
> I wasn't sure what to do here... Xml is I think preferable now that Revapi can handle it, but on the other hand, people with existing setups, could no longer just copy paste the output, because it would suddenly be XML and not JSON that they are set up with...

You could output XML and add a message to run http://revapi.org/modules/revapi-maven-plugin/convert-config-to-xml-mojo.html to convert to the new style maybe?

**Comment by vmassol** [comment]
or output both but it's verbose... or output using the same format that it's declared with in the pom ;)

**Comment by metlos** [comment]
I can't see anything wrong with that config... What does `mvn help:effective-pom` say about the plugin config?

**Comment by vmassol** [comment]
````
     <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <version>0.9.0</version>
        <executions>
          <execution>
            <id>revapi-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <analysisConfiguration>
                <revapi.ignore>
                  <item>
                    <code>java.field.serialVersionUIDUnchanged</code>
                    <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                    <justification>The ExtensionId.hashCode field was wrongly introduced as non transient and
                  deserializing some data serialized with the previous XWiki version should at worse initialize it
                  to the default value which is -1 and ok. In any case we're using the ignoreUnknownElements()
                  option on the XStream side so we should be ok anyway!</justification>
                  </item>
                  <item>
                    <code>java.field.serialVersionUIDUnchanged</code>
                    <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                    <justification>Does not break anything: new static field with no impact on the
                  serialization/unserialization</justification>
                  </item>
                </revapi.ignore>
              </analysisConfiguration>
              <analysisConfigurationFiles>
                <configurationFile>
                  <resource>revapi.json</resource>
                </configurationFile>
              </analysisConfigurationFiles>
              <oldVersion>9.0</oldVersion>
              <skip>false</skip>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.xwiki.commons</groupId>
            <artifactId>xwiki-commons-tool-license-resources</artifactId>
            <version>9.2-SNAPSHOT</version>
            <scope>compile</scope>
          </dependency>
          <dependency>
            <groupId>org.revapi</groupId>
            <artifactId>revapi-java</artifactId>
            <version>0.14.0</version>
            <scope>compile</scope>
          </dependency>
        </dependencies>
       <configuration>
          <analysisConfiguration>
            <revapi.ignore>
              <item>
                <code>java.field.serialVersionUIDUnchanged</code>
                <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                <justification>The ExtensionId.hashCode field was wrongly introduced as non transient and
                  deserializing some data serialized with the previous XWiki version should at worse initialize it
                  to the default value which is -1 and ok. In any case we're using the ignoreUnknownElements()
                  option on the XStream side so we should be ok anyway!</justification>
              </item>
              <item>
                <code>java.field.serialVersionUIDUnchanged</code>
                <new>field org.xwiki.extension.ExtensionId.serialVersionUID</new>
                <justification>Does not break anything: new static field with no impact on the
                  serialization/unserialization</justification>
              </item>
            </revapi.ignore>
          </analysisConfiguration>
          <analysisConfigurationFiles>
            <configurationFile>
              <resource>revapi.json</resource>
            </configurationFile>
          </analysisConfigurationFiles>
          <oldVersion>9.0</oldVersion>
          <skip>false</skip>
        </configuration>
      </plugin>
````

**Comment by vmassol** [comment]
And the error I get on the module I'm building is:

````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.837 s
[INFO] Finished at: 2017-03-17T15:05:48+01:00
[INFO] Final Memory: 80M/798M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "integration-tests" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.9.0:check (revapi-check) on project xwiki-commons-cache-infinispan: The following API problems caused the build to fail:
[ERROR] java.method.addedToInterface: method <C> void org.infinispan.notifications.FilteringListenable<K, V>::addFilteredListener(java.lang.Object, org.infinispan.notifications.cachelistener.filter.CacheEventFilter<? super K, ? super V>, org.infinispan.notifications.cachelistener.filter.CacheEventConverter<? super K, ? super V, C>, java.util.Set<java.lang.Class<? extends java.lang.annotation.Annotation>>) @ org.infinispan.AdvancedCache<K, V>: Method was added to an interface. [org.infinispan:infinispan-core:jar:8.2.6.Final]
[ERROR] java.method.addedToInterface: method <C> void org.infinispan.notifications.FilteringListenable<K, V>::addFilteredListener(java.lang.Object, org.infinispan.notifications.cachelistener.filter.CacheEventFilter<? super K, ? super V>, org.infinispan.notifications.cachelistener.filter.CacheEventConverter<? super K, ? super V, C>, java.util.Set<java.lang.Class<? extends java.lang.annotation.Annotation>>) @ org.infinispan.Cache<K, V>: Method was added to an interface. [org.infinispan:infinispan-core:jar:8.2.6.Final]
[ERROR] java.method.addedToInterface: method <C> void org.infinispan.notifications.FilteringListenable<K, V>::addFilteredListener(java.lang.Object, org.infinispan.notifications.cachelistener.filter.CacheEventFilter<? super K, ? super V>, org.infinispan.notifications.cachelistener.filter.CacheEventConverter<? super K, ? super V, C>, java.util.Set<java.lang.Class<? extends java.lang.annotation.Annotation>>) @ org.infinispan.notifications.cachelistener.CacheNotifier<K, V>: Method was added to an interface. [org.infinispan:infinispan-core:jar:8.2.6.Final]
[ERROR] 
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
...
````

But my guess is that these should't be displayed thanks to the following in the common config:

````
      "filter": {
        "packages": {
          "regex": true,
          // Note that we currently don't include non-XWiki classes in the checks, the reason being that
          // third-party deps break backward-compat or source compat all the time and we would need to have
          // excludes all the time. So we currently trust them that the breakages are not real breakages
          // that will affect us. We should probably improve this in the future.
          "include": [
            "org\\.xwiki\\..*"
          ],
          "exclude": [
            "org\\.xwiki\\..*\\.internal(\\..*)?",
            "org\\.xwiki\\..*\\.test(\\..*)?"
          ]
        }
      }
````

Right?

**Comment by vmassol** [comment]
in your example here I see the format is different than mine: https://github.com/revapi/revapi/commit/616c3a673d56f56c39765b45cc775c84a10a8d22#diff-8a4b09a5230d13427bcd3018f24fd188R1

Could that be it?

**Comment by metlos** [comment]
No, that shouldn't be a problem. What you have is now officially called "old style" of configuration and is/should be still supported...

I'll try to reproduce this locally. I thought I had this covered by integration tests, but truth is that the itests don't inherit the config from parent... Btw. where is `revapi.json` stored in the shared jar?

**Comment by vmassol** [comment]
I've created the file named revapi.json inside this directory: https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources

Thanks again for your help.

**Comment by vmassol** [comment]
Note that I don't mind using a new style (I'd prefer that actually). But not fully sure how to convert to that new style :)

**Comment by vmassol** [comment]
if you prefer I can commit what I have in a branch

**Comment by vmassol** [comment]
ok committed on a branch here: https://github.com/xwiki/xwiki-commons/compare/revapi-inherit-config

**Comment by vmassol** [comment]
ah I have one idea, about the "\" in revapi.json

**Comment by vmassol** [comment]
I've tried with a double backslash but still not working:

````
      {
        "regex": true,
        "code": "java\\.class\\.externalClassExposedInAPI",
        "package": "org\\.xwiki\\..*",
        "justification": "Dragging of other XWiki types to the API is OK."
      }
`````

**Comment by metlos** [comment]
> BTW it's a bit strange that some regexes require double backslash and some other single backslash (see #65 (comment)).

IMHO, those should be all double backslashes... Backslash is an escape character in JSON the same as it is in Java...

**Comment by vmassol** [comment]
Issue fixed, I was using a wrong depenency on my jar containing my revapi.json file. I'm really sorry about that. Thanks for your help again and sorry to have made you loose your time...

**Comment by vmassol** [comment]
@metlos  I'm trying the convert mojo now. I get a NPE:

````
[INFO] ------------------------------------------------------------------------
[INFO] Building XWiki Commons - Core - Parent POM 9.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ xwiki-commons-core ---
[INFO] 
[INFO] --- revapi-maven-plugin:0.9.0:convert-config-to-xml (default-cli) @ xwiki-commons-core ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.908 s
[INFO] Finished at: 2017-03-17T16:34:04+01:00
[INFO] Final Memory: 15M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.9.0:convert-config-to-xml (default-cli) on project xwiki-commons-core: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.9.0:convert-config-to-xml failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.revapi:revapi-maven-plugin:0.9.0:convert-config-to-xml (default-cli) on project xwiki-commons-core: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.9.0:convert-config-to-xml failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.revapi:revapi-maven-plugin:0.9.0:convert-config-to-xml failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.revapi.maven.ConvertToXmlConfigMojo.execute(ConvertToXmlConfigMojo.java:102)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core (master) $ 
````

any idea? :)
