### ISSUE TITLE
Issue with filtering

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#72]
Hi,

I tried to configure revapi in our repo recently and I have faced a couple of issues. Here is the configuration:

https://github.com/MarianMacik/drools/blob/revapi-bug/drools-core/src/build/revapi-config.json#L13

Version of the plugin is 0.8.1 + 0.13.1 for java extension.

I am getting following errors:

1. [ERROR] Failed to scan class org.drools.core.marshalling.impl.ProtobufMessages.ActionQueue.Assert. Analysis results may be skewed.
java.lang.IllegalStateException: Could not determine the element of a type: com.google.protobuf.InvalidProtocolBufferException...
     - I do not understand why it is checking org.drools.core.marshalling.* when I have only org.drools.core.command.* configured.
     - It fails probably because the whole class is generated and thus it is very long and the methods are sometimes very long too.

2.  At the end of the build, I am getting another error:
     - org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.revapi:revapi-maven-plugin:0.8.1:report (report) on project drools-core: Execution report of goal org.revapi:revapi-maven-plugin:0.8.1:report failed: Failed to generate report.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution report of goal org.revapi:revapi-maven-plugin:0.8.1:report failed: Failed to generate report.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalStateException: Failed to generate report.
	at org.revapi.maven.ReportMojo.ensureAnalyzed(ReportMojo.java:402)
	at org.revapi.maven.ReportMojo.executeReport(ReportMojo.java:270)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to analyze archives
	at org.revapi.maven.Analyzer.analyze(Analyzer.java:414)
	at org.revapi.maven.ReportMojo.ensureAnalyzed(ReportMojo.java:397)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.revapi.java.model.TypeElement$1.visitExecutable(TypeElement.java:196)
	at org.revapi.java.model.TypeElement$1.visitExecutable(TypeElement.java:163)
	at com.sun.tools.javac.code.Symbol$MethodSymbol.accept(Symbol.java:1644)
	at org.revapi.java.model.TypeElement.getModel(TypeElement.java:163)
	at org.revapi.java.model.TypeElement.lambda$getUseSites$1(TypeElement.java:121)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.revapi.java.model.TypeElement.getUseSites(TypeElement.java:122)
	at org.revapi.java.spi.JavaTypeElement.visitUseSites(JavaTypeElement.java:39)
	at org.revapi.java.JavaElementDifferenceAnalyzer.appendUses(JavaElementDifferenceAnalyzer.java:357)
	at org.revapi.java.JavaElementDifferenceAnalyzer.endAnalysis(JavaElementDifferenceAnalyzer.java:269)
	at org.revapi.Revapi.analyze(Revapi.java:246)
	at org.revapi.Revapi.analyzeWith(Revapi.java:196)
	at org.revapi.Revapi.analyze(Revapi.java:126)
	at org.revapi.maven.Analyzer.analyze(Analyzer.java:412)
	... 26 more

If you want to reproduce it, just [checkout this branch](https://github.com/MarianMacik/drools/tree/revapi-bug) and run **mvn clean install -X -DskipTests** on drools-core module.

However, when I leave the config from the previous [commit](https://github.com/MarianMacik/drools/blob/36c9abd790d881baabe3b83941124f51e49ef76c/drools-core/src/build/revapi-config.json#L5), only the first issue happens.

Thanks for your help.

Marian

**Comment by metlos** [comment]
Sorry for the lag in response time ;) I will take a look at this...

**Comment by metlos** [comment]
Ok, this is completely stale and I can't reproduce it anymore in the repo and branch provided due compilation errors there. So let's just close this one and open a new issue for the more current codebase.
