### ISSUE TITLE
standalone can get confused by outdated extensions

### ISSUE THREAD

**Issue by simonbasle** [revapi/revapi#73]
While using revapi standalone 0.6.1, I had first tried a wrong command line with out-of-sync or out-of-date dependencies.

When I came together with the *correct* command line, I got a puzzling error.

Command line:
```bash
./revapi.sh --extensions=org.revapi:revapi-basic-features:0.6.0,org.revapi:revapi-java:0.14.0,org.revapi:revapi-reporter-text:0.8.0 --old-gavs groupId:artifactId:oldVersion --new-gavs groupId:artifactId:newVersion
```

Error:
```
Exception in thread "main" java.lang.AbstractMethodError: org.revapi.java.JavaApiAnalyzer.getExtensionId()Ljava/lang/String;
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.revapi.AnalysisContext.addExtensionIds(AnalysisContext.java:222)
	at org.revapi.AnalysisContext.builder(AnalysisContext.java:169)
	at org.revapi.standalone.Main.run(Main.java:307)
	at org.revapi.standalone.Main.main(Main.java:262)
```

It was fixed by cleaning the `extensions` directory in the standalone install directory.

**Comment by metlos** [comment]
I reworked the extension loading in the CLI and should at least warn if there is a potential for such version conflicts between classes bundled in CLI and classes required by the extensions. This is gonna be released with `revapi-standalone-0.7.0`.
