### ISSUE TITLE
RevAPI is not working for mssql-jdbc

### ISSUE THREAD

**Issue by nsidhaye** [revapi/revapi#75]
Your https://diff.revapi.org/  is not working for GroupdId: com.microsoft.sqlserver ArtifactId: mssql-jdbc 

I tried for 6.1.5.jre8-preview & 6.1.6.jre8-preview. 

Even I tried Maven also but no success

**Online Version**
For this I configured only `com.microsoft.sqlserver.jdbc` and uncheck checkbox for Include API From Dependency
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalStateException: Revapi analysis failed with message: Failed to obtain class tree due to compilation failure.
	at org.revapi.aws.lambda.Runner.handle(Runner.java:136)
	at org.revapi.aws.lambda.Runner.main(Runner.java:58)
Caused by: java.lang.IllegalStateException: Failed to obtain class tree due to compilation failure.
	at org.revapi.java.model.JavaElementForest.waitForCompilation(JavaElementForest.java:125)
	at org.revapi.java.model.JavaElementForest.getRoots(JavaElementForest.java:59)
	at org.revapi.Revapi.analyzeWith(Revapi.java:255)
	at org.revapi.Revapi.analyze(Revapi.java:181)
	at org.revapi.aws.lambda.Runner.handle(Runner.java:130)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
	at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException
	at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:78)
	at org.revapi.java.compilation.MissingTypeAwareDelegatingElements.getTypeElement(MissingTypeAwareDelegatingElements.java:54)
	at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1041)
	at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1023)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scan(ClasspathScanner.java:269)
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:118)
	at org.revapi.java.compilation.Compiler.lambda$compile$1(Compiler.java:123)
	at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:52)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.jvm.Code.width(Code.java:279)
	at com.sun.tools.javac.jvm.ClassReader.initParameterNames(ClassReader.java:2082)
	at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:2040)
	at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2252)
	at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2324)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2511)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2442)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:127)
	at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
	at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
	at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:72)
	... 23 more

```

**Maven POM File**
```
[INFO] Generating "API Change Analysis" report    --- revapi-maven-plugin:0.9.1
Downloading: https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/maven-metadata.xml (847 B at 4.2 KB/sec)
[INFO] Comparing [com.microsoft.sqlserver:mssql-jdbc:jar:6.1.6.jre8-preview] against [com.microsoft.sqlserver:mssql-jdbc:jar:6.1.7-SNAPSHOT] (including their transitive dependencies).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.837 s
[INFO] Finished at: 2017-04-28T18:47:20-07:00
[INFO] Final Memory: 65M/778M
```

**Comment by metlos** [comment]
Interesting... The stack trace reveals an NPE inside javac itself...

**Comment by nsidhaye** [comment]
@metlos I am not sure, this might be due to optional dependencies. Locally I able to compile mssql project with maven without any problem,.

**Comment by metlos** [comment]
This is now working as can be seen on https://diff.revapi.org/?groupId=com.microsoft.sqlserver&artifactId=mssql-jdbc&old=6.1.5.jre8-preview&new=6.1.6.jre8-preview

The above mentioned fixes are now used by the site.

Thanks for reporting the problem!
