### ISSUE TITLE
NPE on attempt to compare org.jetbrains.kotlin:kotlin-stdlib:1.0.6 and 1.1.2-2

### ISSUE THREAD

**Issue by serejke** [revapi/revapi#76]
I've faced an exception on https://diff.revapi.org/:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalStateException: Revapi analysis failed with message: Failed to obtain class tree due to compilation failure.
	at org.revapi.aws.lambda.Runner.handle(Runner.java:136)
	at org.revapi.aws.lambda.Runner.main(Runner.java:58)
Caused by: java.lang.IllegalStateException: Failed to obtain class tree due to compilation failure.
	at org.revapi.java.model.JavaElementForest.waitForCompilation(JavaElementForest.java:125)
	at org.revapi.java.model.JavaElementForest.getRoots(JavaElementForest.java:59)
	at org.revapi.Revapi.analyzeWith(Revapi.java:256)
	at org.revapi.Revapi.analyze(Revapi.java:181)
	at org.revapi.aws.lambda.Runner.handle(Runner.java:130)
	... 1 more
	Suppressed: java.lang.IllegalStateException: Exception thrown while waiting for compilation to end for clean up
		at org.revapi.java.compilation.CompilationValve.removeCompiledResults(CompilationValve.java:77)
		at org.revapi.java.JavaElementDifferenceAnalyzer.close(JavaElementDifferenceAnalyzer.java:157)
		at org.revapi.Revapi.analyzeWith(Revapi.java:268)
		... 3 more
	Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.NullPointerException
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.revapi.java.compilation.CompilationValve.removeCompiledResults(CompilationValve.java:72)
		... 5 more
	Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.NullPointerException
		at com.sun.tools.javac.main.Main.compile(Main.java:553)
		at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
		at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
		at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
		at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:80)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.IllegalStateException: java.lang.NullPointerException
		at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:78)
		at org.revapi.java.compilation.MissingTypeAwareDelegatingElements.getTypeElement(MissingTypeAwareDelegatingElements.java:54)
		at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1041)
		at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1023)
		at org.revapi.java.compilation.ClasspathScanner$Scanner.scan(ClasspathScanner.java:269)
		at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:118)
		at org.revapi.java.compilation.Compiler.lambda$compile$1(Compiler.java:123)
		at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:52)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
		at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
		at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
		at com.sun.tools.javac.main.Main.compile(Main.java:523)
		... 8 more
	Caused by: java.lang.NullPointerException
		at com.sun.tools.javac.jvm.Code.width(Code.java:279)
		at com.sun.tools.javac.jvm.ClassReader.initParameterNames(ClassReader.java:2082)
		at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:2040)
		at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2252)
		at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2324)
		at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2511)
		at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2442)
		at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
		at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
		at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
		at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
		at com.sun.tools.javac.jvm.ClassReader.completeEnclosing(ClassReader.java:2475)
		at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2436)
		at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
		at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
		at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
		at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
		at com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:127)
		at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
		at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
		at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:72)
		... 23 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
	at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException
	at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:78)
	at org.revapi.java.compilation.MissingTypeAwareDelegatingElements.getTypeElement(MissingTypeAwareDelegatingElements.java:54)
	at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1041)
	at org.revapi.java.spi.Util.findTypeByBinaryName(Util.java:1023)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scan(ClasspathScanner.java:269)
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:118)
	at org.revapi.java.compilation.Compiler.lambda$compile$1(Compiler.java:123)
	at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:52)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.jvm.Code.width(Code.java:279)
	at com.sun.tools.javac.jvm.ClassReader.initParameterNames(ClassReader.java:2082)
	at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:2040)
	at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2252)
	at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2324)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2511)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2442)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.jvm.ClassReader.loadClass(ClassReader.java:2623)
	at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1907)
	at com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:2146)
	at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:384)
	at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:375)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
	at com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:371)
	at com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:705)
	at com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:125)
	at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
	at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
	at org.revapi.java.spi.IgnoreCompletionFailures.in(IgnoreCompletionFailures.java:72)
	... 23 more

**Comment by metlos** [comment]
Revapi is using the java compiler under the hood to get at the model of the classes in the analyzed jar files. This NPE comes deep from javac itself. Not sure if this is caused by me misusing the compiler of if it is a genuine bug in javac.

Since this is already a second instance of this problem in the couple of days people started to use diff.revapi.org, I think I will have to figure out a reproducer and see what Oracle has to say about this...

Thanks for reporting it!

**Comment by metlos** [comment]
https://diff.revapi.org has been updated with the revapi version containing the above fixes and the artifact can now be compared - https://diff.revapi.org/?groupId=org.jetbrains.kotlin&artifactId=kotlin-stdlib&old=1.0.6&new=1.1.2-2

Thanks for reporting the problem!
