### ISSUE TITLE
Maven plugin not working?

### ISSUE THREAD

**Issue by covolution** [revapi/revapi#9]
If I use the configuration described in Issue #8 , I get the following error when I run ` mvn revapi:check -X`

```
org.revapi:revapi-maven-plugin:0.3.1:check failed: file cannot be null
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: file cannot be null
	at org.revapi.maven.FileArchive.<init>(FileArchive.java:38)
	at org.revapi.maven.Analyzer$1.apply(Analyzer.java:208)

```

**Comment by metlos** [comment]
Did you make any progress on this with maven plugin `0.3.2`? I didn't really fix anything there though I added some logging that could help us diagnose why you are seeing this.

**Comment by metlos** [comment]
I hope this is fixed with the new examples on the site and a much more robust handling of artifact resolution problems in the maven plugin.

If the problem persists, please raise a new issue.
