### ISSUE TITLE
AbstractMethodError in AnalysisContext

### ISSUE THREAD

**Issue by fancsi** [revapi/revapi#93]
I'm trying to run the CLI or the ant version but both have the same problem
```
$ ./revapi.sh --extensions=org.revapi:revapi-java:0.14.1,org.revapi:revapi-reporting-text:0.4.1 -o Api-release-old.aar -n Api-release.aar -D revapi.reporter.text.minSeverity=BREAKING
Exception in thread "main" java.lang.AbstractMethodError
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.revapi.AnalysisContext.addExtensionIds(AnalysisContext.java:230)
        at org.revapi.AnalysisContext.builder(AnalysisContext.java:172)
        at org.revapi.standalone.Main.run(Main.java:307)
        at org.revapi.standalone.Main.main(Main.java:262)
```

**Comment by metlos** [comment]
Huh... In CLI, sometimes it helps to clear out the extensions directory... What version of CLI/Ant task are you using? There's been some API changes in Revapi recently, so maybe you're facing that...

**Comment by fancsi** [comment]
Yeah, the version was the problem, I tried using the latest version of all components (standalone:0.6.2 which uses revapi:0.8.2, and then run with extensions revapi-java:0.14.1 and revapi-reporting-text:0.4.1).

I managed to get it work with the standalone version 0.5.1 and extensions: revapi-java:0.6.3 and revapi-reporting-text:0.4.1

**Comment by metlos** [comment]
Latest versions of components should work together.. Please refer to https://revapi.org/downloads.html for the latest version numbers..

I don't have the opportunity to test this right now, so I'm reopening this issue so that it doesn't fall under the radar until either you or me test that latest versions are indeed compatible..

**Comment by marcphilipp** [comment]
I'm having the same problem using version 0.6.4 of the standalone CLI:

```
$ ./revapi.sh \  
     --extensions=org.revapi:revapi-basic-features:0.6.3,org.revapi:revapi-java:0.14.4,org.revapi:revapi-reporter-text:0.8.2 \
     --old-gavs=org.junit.jupiter:junit-jupiter-api:5.0.0 \
     --new-gavs=org.junit.jupiter:junit-jupiter-api:5.0.1
Exception in thread "main" java.lang.AbstractMethodError
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.revapi.AnalysisContext.addExtensionIds(AnalysisContext.java:230)
	at org.revapi.AnalysisContext.builder(AnalysisContext.java:172)
	at org.revapi.standalone.Main.run(Main.java:307)
	at org.revapi.standalone.Main.main(Main.java:262)

$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by metlos** [comment]
I've been neglecting CLI for some time now, concentrating mostly on the maven plugin and it starts to show..

I suppose you tried deleting the extensions directory to rule out interference with old versions of the components?

If that is the case, I would need to take a proper look at the aging CLI code and see WTH is wrong with it all the time..

If you had some spare cycles to contribute, I'd be more than happy to assist you in fixing it.

**Comment by marcphilipp** [comment]
> I suppose you tried deleting the extensions directory to rule out interference with old versions of the components?

I did.

> If you had some spare cycles to contribute, I'd be more than happy to assist you in fixing it.

I've tried using 0.6.3 of the cli and that worked.

**Comment by metlos** [comment]
I've modified the CLI to not use JBoss Forge but rather Maven and JBoss Modules directly, which enabled me to add some warnings when there is a mismatch between the bundled version of Revapi API and the one required by the extensions. Hopefully, that will make errors like this more understandable to the users...

This will be part of `revapi-standalone-0.7.0`.

**Comment by metlos** [comment]
`revapi-standalone-0.7.0` has been released and should offer better diagnostics of such compatibility problems between Revapi versions.
