### ISSUE TITLE
AntReporter cannot be instantiated

### ISSUE THREAD

**Issue by fancsi** [revapi/revapi#94]
https://github.com/revapi/revapi/blob/2ca021bed59d97bb524d17245b4a6b67857c5b85/revapi-ant-task/src/main/java/org/revapi/ant/RevapiTask.java#L105

Caused by: java.lang.IllegalStateException: Class class org.revapi.ant.AntReporter does not have a public no-arg constructor.
	at org.revapi.AnalysisContext.instantiate(AnalysisContext.java:229)
	at org.revapi.AnalysisContext.addExtensionIds(AnalysisContext.java:222)
	at org.revapi.AnalysisContext.builder(AnalysisContext.java:172)
	at org.revapi.ant.RevapiTask.initAnalysisContext(RevapiTask.java:117)
	at org.revapi.ant.RevapiTask.execute(RevapiTask.java:71)
Caused by: java.lang.IllegalAccessException: Class org.revapi.AnalysisContext can not access a member of class org.revapi.ant.AntReporter with modifiers ""
	at org.revapi.AnalysisContext.instantiate(AnalysisContext.java:227)

I guess the problem is the AntReporter is package private and the AnalysisContext cannot instantiate it.

**Comment by metlos** [comment]
This should be fixed in `revapi-ant-task` `0.6.2`.
